version: "3"
services:
  api-gateway:
    build: "./customers-service"
    depends_on:
      - customers-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  customers-service:
    build: "./customers-service"
    depends_on:
      - customers-service-db
    environment:
      - DB_URI=mysql://root:password@customers-service-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./customers-service:/opt/app

  customers-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306
